name: vibevoice_flutter_demo
description: Demo app to run VibeVoice TTS examples (educational).
publish_to: none
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.4.0
  just_audio: ^0.9.36
  audio_session: ^0.1.14
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
